version: "3.8"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./getvite_app:/app
    stdin_open: true

  api:
    build: getvite_api/.
    command: sh -c "flask run"
    ports:
      - 5000:5000
    working_dir: /api
    volumes:
      - ./getvite_api:/api
    stdin_open: true
